SET SCHEMA CODEJAM;

CREATE ROW TABLE BIKE_STATIONS (
	ID int PRIMARY KEY,
	STATION_NAME VARCHAR(200),
	AVAILABLE_DOCKS INT,
	TOTAL_DOCKS INT,
	STATUS_VALUE VARCHAR(16),
	AVAILABLE_BIKES INT,
	ADDRESS_1 VARCHAR(200)

)