IMPORT FROM CSV FILE '/hana/shared/HXE/HDB90/work/201701-citibike-tripdata.csv'
into "CODEJAM"."TRIPS"
WITH COLUMN LIST (TRIP_DURATION, START_TIME, STOP_TIME,	START_STATION_ID, START_STATION_NAME, START_LATITUDE, START_LONGITUDE, END_STATION_ID, END_STATION_NAME, END_LATITUDE, END_LONGITUDE, BIKE_ID, USER_TYPE, BIRTH_YEAR, GENDER)
SKIP FIRST 1 ROW
record delimited by '\n'
field delimited by ','
error log '/hana/shared/HXE/HDB90/work/import_csv.bad';