info:
  name: Get all deployments
  type: http
  seq: 6

http:
  method: GET
  url: "{{ai_api_url}}/lm/deployments"
  headers:
    - name: Authorization
      value: Bearer {{access_token}}
    - name: AI-Resource-Group
      value: "{{resource_group}}"
    - name: Content-Type
      value: application/json
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: example
    request:
      url: "{{AI_API}}/lm/deployments"
      method: GET
      headers:
        - name: Authorization
          value: Bearer {{access_token}}
        - name: AI-Resource-Group
          value: "{{resource-group}}"
        - name: Content-Type
          value: application/json
    response:
      status: 200
      statusText: OK
      headers:
        - name: date
          value: Thu, 26 Mar 2026 12:41:25 GMT
        - name: content-type
          value: application/json
        - name: content-length
          value: "751"
        - name: access-control-allow-origin
          value: "null"
        - name: access-control-allow-credentials
          value: "false"
        - name: cache-control
          value: no-store, must-revalidate
        - name: x-upstream-service-time
          value: "40"
      body:
        type: json
        data: |-
          {
            "count": 1,
            "resources": [
              {
                "id": "db664f32e41f2694",
                "createdAt": "2026-03-26T11:44:12Z",
                "modifiedAt": "2026-03-26T11:44:12Z",
                "status": "RUNNING",
                "details": {
                  "scaling": {
                    "backendDetails": {},
                    "backend_details": {}
                  },
                  "resources": {
                    "backendDetails": {},
                    "backend_details": {}
                  }
                },
                "scenarioId": "orchestration",
                "configurationId": "a660a213-5933-4b2c-872b-c1dbb3e771c2",
                "latestRunningConfigurationId": "a660a213-5933-4b2c-872b-c1dbb3e771c2",
                "lastOperation": "CREATE",
                "targetStatus": "RUNNING",
                "submissionTime": "2026-03-26T11:45:18Z",
                "startTime": "2026-03-26T11:46:33Z",
                "configurationName": "orchestration-config",
                "deploymentUrl": "https://api.ai.internalprod.eu-central-1.aws.ml.hana.ondemand.com/v2/inference/deployments/db664f32e41f2694"
              }
            ]
          }
