apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: tf-text-clf-serve
  annotations:
    scenarios.ai.sap.com/description: "Tensorflow text classification"
    scenarios.ai.sap.com/name: "movie-review-clf"
    executables.ai.sap.com/description: "Tensorflow GPU Serving executable"
    executables.ai.sap.com/name: "serve-executable"
  labels:
    scenarios.ai.sap.com/id: "tf-text-clf"
    ai.sap.com/version: "1.0.0"
spec:
  inputs:
    artifacts:
    - name: modelArtifact
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      labels: |
        ai.sap.com/resourcePlan: infer.s
    spec: |
      predictor:
        imagePullSecrets:
          - name: docker-registry-secret
        containers:
        - name: kfserving-container
          image: "docker.io/YOUR_DOCKER_USER_NAME/movie-review-clf-serve:0.0.1"
          ports:
            - containerPort: 9001
              protocol: TCP
          env:
            - name: STORAGE_URI
              value: "{{inputs.artifacts.modelArtifact}}"
