apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: text-clf-infer-tutorial # Executable ID (max length 64 lowercase-hypen-separated), please modify this to any value if you are not the only user of your SAP AI Core instance. Example: `text-clf-infer-tutorial-1234`
  annotations:
    scenarios.ai.sap.com/description: "SAP AI Core tutorial scenario"
    scenarios.ai.sap.com/name: "text-clf-tutorial-scenario"
    executables.ai.sap.com/description: "Inference executable for text classification with Scikit-learn"
    executables.ai.sap.com/name: "text-clf-infer-tutorial-exec"
  labels:
    scenarios.ai.sap.com/id: "text-clf-tutorial"
    ai.sap.com/version: "1.0.0"
spec:
  inputs:
    parameters: []
    artifacts:
      - name: textmodel
  template:
    apiVersion: "serving.kubeflow.org/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: starter
    spec: |
      predictor:
        imagePullSecrets:
          - name: docker-registry-secret
        minReplicas: 1
        maxReplicas: 5
        containers:
        - name: kfserving-container
          image: "docker.io/<your-username>/text-clf-serve:0.0.1"
          ports:
            - containerPort: 9001
              protocol: TCP
          env:
            - name: STORAGE_URI
              value: "{{inputs.artifacts.textmodel}}"
